### ISSUE TITLE
Test failed at exercise "ex3" monix-task-exersices, even for reference solution.

### ISSUE THREAD

**Issue by sashamc** [scalazone/monix-exercises#3]
**Bug description**
When running command 
```bash
sbt "monix-task-exercises/testOnly *ResourceSafetyExercisesTests"
```
from the monix-exercises folder, test reports failure:
> - ResourceSafetyExercises.ex3 *** FAILED ***
> Some(Success((1,2))) did not equal None (ResourceSafetyExercisesTests.scala:141)
> Analysis:
> Some(value: Success((1,2)) -> )
> Run completed in 995 milliseconds.

This occurs even with ex3 function implementation from lesson6/ResourceSafetyExercisesSolutions.scala.

**Environment**
sbt 1.5.2 (AdoptOpenJDK Java 16.0.1)
macOS 10.15.7 Darwin Kernel Version 19.6.0 RELEASE_X86_64

**Additional context**
In the [test file](https://github.com/scalazone/monix-exercises/blob/main/monix-task-exercises/src/test/scala/scalazone/monix/lesson6/ResourceSafetyExercisesTests.scala) 
lines 141, 144 probably contain mistype 'f1' instead of 'f2'. 
```scala
138:  val f2 = ResourceSafetyExercises.ex3(() => inputStream).runToFuture
141:  f1.value shouldEqual None
142:  f2.cancel()
144:  f1.value shouldEqual None
```

**Comment by FranklinChen** [comment]
I confirmed that the test for the solution fails.

**Comment by Avasil** [comment]
I'll look into it, thanks
